### ISSUE TITLE
O endereço de api esta  bloqueado para fora do dominio

### ISSUE THREAD

**Issue by enieber** [belezanaweb/test-app#11]
Fiz quase todo o app, quando fui fazer a integração com dados reais, descobri que a um bloqueio de host no header da request, provavelmente a configuração de cors está ativa.

## Como reproduzir

se é feito um request usando curl para o endpoint retorna 400

```

curl https://pacific-wave-51314.herokuapp.com/products?page=1&size=10
```

mas se for adicionado um host valido a resposta é 200:

```
curl -H "Origin: pacific-wave-51314.herokuapp.com https://pacific-wave-51314.herokuapp.com/products?page=1&size=10
```

**Comment by fontesrp** [comment]
Bom dia @enieber,

Não conseguimos reproduzir seu erro. A requisição sempre retorna 200, independente dos Headers.

De qualquer forma, habilitei o CORS no Express [aqui](https://github.com/belezanaweb/test-app/commit/76e8f2087ca2c9c6a27e75ed4332cca0831c963c). Ele agora vai passar o header `Access-Control-Allow-Origin: *` em todas as respostas.

```
$ curl \
  "https://pacific-wave-51314.herokuapp.com/products" \
  -v \
  -G \
  -d "page=1" \
  -d "size=10"

> GET /products?page=1&size=10 HTTP/1.1
> Host: pacific-wave-51314.herokuapp.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: Cowboy
< Connection: keep-alive
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Content-Type: application/json; charset=utf-8
< Content-Length: 313048
< Etag: W/"4c6d8-a4bmhVRpgsS4bJoMimHGpmS5mpQ"
< Date: Mon, 20 Apr 2020 11:59:22 GMT
< Via: 1.1 vegur
< 
```

Vou fechar a issue porque não é reproduzível. Boa sorte com o teste! Nos conta se tiver mais algum problema 😉
